version: '3.1'

services:
  users-front:
    container_name: users-front
    build: ./Users-Front
    ports:
      - '3002:3002'
  home:
    container_name: home
    build: ./Home
    ports:
      - '3000:3000'
    depends_on:
      - users-front
