version: "3"
services:
  sample:
    container_name: react-pwa
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
