version: '3.1'

services:
  Home:
    container_name: Home
    build: ./Home
    ports:
      - '3000:3000'
  Users-Front:
    container_name: Users-Front
    build: ./Users-Front
    ports:
      - '3002:3002'
